### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by atrueresistance** [MotorDynamicsLab/LDO-Milo-V1.5#2]
[[a] Z Axis Cable Cover x1_LDO.stl](https://github.com/MotorDynamicsLab/LDO-Milo-V1.5/blob/master/STLs/Minimill%20Main/Cable%20Chain%20Mounts/[a]%20Z%20Axis%20Cable%20Cover%20x1_LDO.stl)	Minimill Main/Cable Chain Mounts

![image](https://github.com/MotorDynamicsLab/LDO-Milo-V1.5/assets/7239809/657cb15c-3019-4405-8a1d-b68a89ea76a5)

**Comment by camerony** [comment]
This is fixed, the file was renamed.
